# Generated by Django 5.1.3 on 2024-11-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('PNTS', 'Prefer not to say'), ('O', 'Other')], max_length=5)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('place_of_death', models.CharField(blank=True, max_length=100, null=True)),
                ('living_status', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies_and_interests', models.TextField(blank=True, null=True)),
                ('notable_achievements', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('genetic_information', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('family_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('notable_ancestry_events', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('family_role', models.CharField(blank=True, max_length=50, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('favorite_family_traditions', models.TextField(blank=True, null=True)),
                ('documents', models.ManyToManyField(blank=True, to='familyMembers.document')),
                ('grandparents', models.ManyToManyField(blank=True, related_name='grandchildren', to='familyMembers.member')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='familyMembers.member')),
                ('siblings', models.ManyToManyField(blank=True, to='familyMembers.member')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouses', to='familyMembers.member')),
                ('photos', models.ManyToManyField(blank=True, to='familyMembers.photo')),
                ('videos', models.ManyToManyField(blank=True, to='familyMembers.video')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ('date_of_birth',),
            },
        ),
    ]
