# Generated by Django 5.1.3 on 2024-11-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyMembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='oriki',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
